export const Mock = {
  user: {
    login: { code: 200, msg: 'success', data: { token: 'eyJ...', isAuditor: true } },
    register: { code: 200, msg: 'success', data: true },
    logout: { code: 200, msg: 'success', data: true },
    info: {
      code: 200,
      msg: 'success',
      data: {
        phone: '13565888888',
        orgType: 0,
        orgName: 'HL',
        name: 'HL',
        avatarUrl: 'https://...',
        technology: 'Java,NestJS',
        latitude: 30.12,
        longitude: 120.12,
        technologyTag: 'Java,NestJS',
      },
    },
  },
  project: {
    hall: {
      code: 200,
      msg: 'success',
      data: {
        records: [
          {
            id: 'P2024112801',
            projectName: '项目A',
            technology: 'Java',
            request: '需求',
            category: 'A',
            createTime: '2025-11-28T08:00:00Z',
            annexList: [{ id: 'A1', name: '附件A', thumbnail: 'https://...', url: 'https://...', expireTime: '2025-12-01T00:00:00Z' }],
          },
        ],
        total: 1,
        current: 1,
        size: 10,
        pages: 1,
      },
    },
    list: {
      code: 200,
      msg: 'success',
      data: {
        records: [
          {
            id: 'P2024112801',
            projectName: '项目A',
            status: '开启',
            auditStatus: '审核通过',
            createTime: '2025-11-28T08:00:00Z',
          },
        ],
        total: 1,
        current: 1,
        size: 10,
        pages: 1,
      },
    },
    detail: {
      code: 200,
      msg: 'success',
      data: {
        id: 'P2024112801',
        projectName: '项目A',
        status: '推送关闭',
        auditStatus: '审核中',
        auditRemark: '',
        createTime: '2025-11-28T08:00:00Z',
        technology: 'Java',
        request: '需求',
        annexList: [{ id: 'A1', name: '附件A', thumbnail: 'https://...', url: 'https://...', expireTime: '2025-12-01T00:00:00Z' }],
        projectUserVOList: [{ name: 'HL', phone: '13565888888', takeTime: '2025-11-28T08:00:00Z' }],
      },
    },
    push: { code: 200, msg: 'success', data: true },
    delete: { code: 200, msg: 'success', data: true },
    add: { code: 200, msg: 'success', data: true },
    update: { code: 200, msg: 'success', data: true },
    myAuditList: {
      code: 200,
      msg: 'success',
      data: {
        records: [{ id: 'P2024112801', projectName: '项目A', auditStatus: '待审核', publisher: 'HL' }],
        total: 1,
        current: 1,
        size: 10,
        pages: 1,
      },
    },
    updateAudit: { code: 200, msg: 'success', data: true },
    take: { code: 200, msg: 'success', data: true },
    myTakeList: {
      code: 200,
      msg: 'success',
      data: {
        records: [
          {
            id: 'P2024112801',
            projectName: '项目A',
            status: '开启',
            contact: 'HL',
            phone: '13565888888',
            annexList: [{ id: 'A1', name: '附件A', thumbnail: 'https://...', url: 'https://...', expireTime: '2025-12-01T00:00:00Z' }],
            takeTime: '2025-11-28T08:00:00Z',
          },
        ],
        total: 1,
        current: 1,
        size: 10,
        pages: 1,
      },
    },
  },
  file: {
    upload: { code: 200, msg: 'success', data: true },
    getUrl: { code: 200, msg: 'success', data: 'https://...' },
    del: { code: 200, msg: 'success', data: true },
  },
  system: {
    sms: { code: 200, msg: 'success', data: 32280 },
    dict: {
      code: 200,
      msg: 'success',
      data: [
        {
          dictCode: 1,
          fatherId: 0,
          dictType: 'sys_technology',
          dictSort: 1,
          dictLabel: 'Java',
          dictValue: 'Java',
          status: 0,
        },
      ],
    },
  },
}
